# Generated by Django 4.1.2 on 2023-05-09 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='finder/image/')),
                ('location', models.CharField(max_length=255)),
                ('min_sellary', models.IntegerField()),
                ('resume', models.FileField(upload_to='finder/image/')),
                ('phone', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
