# Generated by Django 4.1.2 on 2023-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder',
            name='min_sellary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finder',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='finder/image/'),
        ),
        migrations.AlterField(
            model_name='finder',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='finder/image/'),
        ),
        migrations.AlterField(
            model_name='finder',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
