# Generated by Django 4.1.2 on 2023-06-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_finder_min_sellary_alter_finder_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
